# vi gatway.yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: bullet-train-gateway
  namespace: jp-bullet-train-gtw
spec:
  gatewayClassName: nginx
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
    hostname: "bullet.train.io"
    tls:
     certificateRefs:
      - group: "" # core API group
        kind: Secret
        name: bullet-train-tls


---
# vi http.yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: bullet-train-route
  namespace: jp-bullet-train-gtw
spec:
  parentRefs:
  - name: bullet-train-gateway
  hostnames:
  - "bullet.train.io"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /available
    backendRefs:
    - name: available
      port: 80
      namespace: jp-bullet-train-app-prod
  - matches:
    - path:
        type: PathPrefix
        value: /books
    backendRefs:
    - name: books
      port: 80
      namespace: jp-bullet-train-app-prod
  - matches:
    - path:
        type: PathPrefix
        value: /travellers
    backendRefs:
    - name: travellers
      port: 80
      namespace: jp-bullet-train-app-prod


# k apply -f gatway.yaml
# k apply -f http.yaml
# k get gateway -n jp-bullet-train-gtw
# k get httproute -n jp-bullet-train-gtw
# vi /etc/hosts and add the following line:
# 127.0.0.1 bullet.train.io (get the ip of the gateway load balancer by running the command: k get gateway bullet-train-gateway -n jp-bullet-train-gtw)
