# vi networkpolicy.yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-multi-pod-ingress
  namespace: isolated
spec:
  podSelector:
    matchLabels:
      app: api
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: frontend
          role: proxy
          
    ports:
    - protocol: TCP
      port: 7000

# k apply -f networkpolicy.yaml
# k get networkpolicy -n isolated
# k get pods -n isolated
# k exec -n isolated podname -- wget -qO- svc:7000 (this should work)
