# k get deployments.apps -n iot-sys sensor-api 
# k get pods -n iot-sys -l app=sensor-api
# k autoscale deployment -n iot-sys sensor-api --min=2 --max=8 --memory=80% --cpu=80% --dry-run=client -o yaml > hpa.yaml
# edit the yaml file to add the scaledown behavour and then apply it using kubectl apply -f hpa.yaml

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sensor-hpa
  namespace: iot-sys
spec:
  maxReplicas: 8
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  - resource:
      name: memory
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sensor-api
  behavior:
   scaleDown:
    stabilizationWindowSeconds: 5


 # This YAML file defines a HorizontalPodAutoscaler (HPA) for the "sensor-api" deployment in the "iot-sys" namespace. The HPA will automatically scale the number of replicas of the "sensor-api" deployment based on CPU and memory utilization. The HPA will maintain a minimum of 2 replicas and can scale up to a maximum of 8 replicas. The target average utilization for both CPU and memory is set to 80%. Additionally, the scale-down behavior is configured with a stabilization window of 5 seconds, which means that after scaling down, the HPA will wait for 5 seconds before allowing another scale-down action to prevent rapid fluctuations in the number of replicas. 
 # the average will be calculated over the last 5 seconds, and if the average utilization is below 80% for both CPU and memory, the HPA will scale down the number of replicas.
 # 80% is for the request of the resources, not the limit. The HPA will use the resource requests to determine the average utilization. If the average utilization is above 80% for either CPU or memory, the HPA will scale up the number of replicas.